const MINUTE_MS = 60_000;
const DAY_SECONDS = 86_400;

export const SEARCH_CONFIG = {
    cacheVersion: "ai-search-v1",
    cacheSeconds: DAY_SECONDS,
    rateWindowMs: MINUTE_MS,
    searchPerMinute: 30,
    maxQueryLength: 600,
    maxDates: 7,
    maxCandidates: 200,
    maxResults: 12,
    maxCurated: 6,
    minGoodResults: 3,
    goodScore: 0.45,
    closestFallbackCount: 3,
    rrfK: 60,
    weights: { feature: 0.35, price: 0.2, shootType: 0.1, distance: 0.15, rating: 0.15, instant: 0.05 },
    missingNeedPenalty: 0.1,
    budgetSoftOverRatio: 0.3,
    distanceHalfScoreKm: 8,
    areaCaveatKm: 3,
    rating: { priorMean: 4.3, priorWeight: 5 },
    timeoutsMs: { parse: 4000, embed: 800, reasons: 9000, index: 15000 },
    ai: {
        models: { gemini: ["gemini-3.5-flash-lite", "gemini-3.1-flash-lite"], embedding: "@cf/baai/bge-m3" },
        perModelPerMinute: 14,
        embedPerMinute: 60,
        perClientPerMinute: 6,
        breakerDefaultMs: MINUTE_MS,
        reasonsTopN: 3,
    },
    sessionTtlMs: 90 * DAY_SECONDS * 1000,
    suggest: { minChars: 2, limit: 6, debounceMs: 200, perMinute: 240, indexSeconds: 600, prefixExpansions: 3, recentLimit: 5 },
    prompt: "Describe your shoot, or search a studio or area",
    promptShort: "Describe your shoot",
    hintIntervalMs: 4000,
    examples: [
        "Product shoot near Gomti Nagar next Saturday, 6 people",
        "Podcast studio in Noida tomorrow, 2 people, 3 hours",
        "Boho pre-wedding shoot in Gurgaon this weekend",
        "Reels shoot in Lucknow, 4 log, kal 2 ghante",
    ],
    searchDocReviewSnippets: 5,
    searchDocMaxChars: 4000,
} as const;
